
using System;

namespace ModelGraph.Core
{
    //=========================================================================
    // specific naming conventions and category of usage, evolve with actual use, (avoid bloating with as yet unused future items) 
    //=========================================================================
    // suffix : none : unique reusabe text string, (put all reusable text first so the nummeric enum value < 256) usage: {byte _kind; var enu = (ResText)_kind; }  
    // suffix : "_E" : specify event static text     (event)
    // suffix : "_F" : specify event formated text   (formated) üsed with string.Format(<localized_text>, arg0,  arg1,..);
    // suffix : "_S" : specify item tooltip text     (summary)
    // suffix : "_V" : specify item description text (verbose)
    // suffix : "_Z" : specify start of a sequence   (zero) e.g. {var enu = (ResText)(index + 1 + (int)ResText.PathType_Z); }
    //=========================================================================
    // _coreResources.resw // resource keys are strings of the form  Enum.GetNames(typeof(ResText));
    // The ResText enum will prevent duplicate entries and we can find all references of every item.
    // We can freely rearrange or insert new values into the ResText enum without messing anybody up. 
    // We can store the ResText enum value in ushort a variable or in some cases in a byte varible.
    // e.g. static byte _itemKind = (byte)ResText.Column; var kind = Localize(((ResText)_itemKind).ToString());
    //=========================================================================
    /// <summary>Unique resource string key</summary>
    internal enum ResText : ushort
    {
        Unassigned,
        Invalid,
        Item,
        Name,
        Column,
        Property,
        Compute,
        Relation,
        ValueType,
        Pairing,
        Labeling,

        ValueTypeEnum_S,
        ValueTypeEnum_Z,
        ValueType_Bool,
        ValueType_BoolArray,
        ValueType_Char,
        ValueType_CharArray,
        ValueType_Byte,
        ValueType_ByteArray,
        ValueType_SByte,
        ValueType_SByteArray,
        ValueType_Int16,
        ValueType_Int16Array,
        ValueType_UInt16,
        ValueType_UInt16Array,
        ValueType_Int32,
        ValueType_Int32Array,
        ValueType_UInt32,
        ValueType_UInt32Array,
        ValueType_Int64,
        ValueType_Int64Array,
        ValueType_UInt64,
        ValueType_UInt64Array,
        ValueType_Single,
        ValueType_SingleArray,
        ValueType_Double,
        ValueType_DoubleArray,
        ValueType_Decimal,
        ValueType_DecimalArray,
        ValueType_DateTime,
        ValueType_DateTimeArray,
        ValueType_String,
        ValueType_StringArray,

        PairingEnum_S,
        PairingEnum_Z,
        Pairing_OneToOne,
        Pairing_OneToMany,
        Pairing_ManyToMany,

        AspectEnum_S,
        AspectEnum_Z,
        Aspect_Point,
        Aspect_Square,
        Aspect_Vertical,
        Aspect_Horizontal,

        LabelingEnum_S,
        LabelingEnum_Z,
        Labeling_None,
        Labeling_Top,
        Labeling_Left,
        Labeling_Right,
        Labeling_Bottom,
        Labeling_Center,
        Labeling_TopLeft,
        Labeling_TopRight,
        Labeling_BottomLeft,
        Labeling_BottomRight,
        Labeling_TopLeftSide,
        Labeling_TopRightSide,
        Labeling_TopLeftCorner,
        Labeling_TopRightCorner,
        Labeling_BottomLeftSide,
        Labeling_BottomRightSide,
        Labeling_BottomLeftCorner,
        Labeling_BottomRightCorner,

        FlipRotateEnum_S,
        FlipRotateEnum_Z,
        FlipRotate_None,
        FlipRotate_FlipVertical,
        FlipRotate_FlipHorizontal,
        FlipRotate_FlipBothWays,
        FlipRotate_RotateClockwise,
        FlipRotate_RotateFlipVertical,
        FlipRotate_RotateFlipHorizontal,
        FlipRotate_RotateFlipBothWays,

        ResizingEnum_S,
        ResizingEnum_Z,
        Resizing_Auto,
        Resizing_Fixed,
        Resizing_Manual,

        NamingEnum_S,
        NamingEnum_Z,
        Naming_None,
        Naming_Default,
        Naming_UniqueNumber,
        Naming_Alphabetic,
        Naming_SubstituteParent,

        BarWidthEnum_S,
        BarWidthEnum_Z,
        BarWidth_Thin,
        BarWidth_Wide,
        BarWidth_ExtraWide,

        ContactEnum_S,
        ContactEnum_Z,
        Contact_Any,
        Contact_One,
        Contact_None,

        SideEnum_S,
        SideEnum_Z,
        Side_Any,
        Side_East,
        Side_West,
        Side_North,
        Side_South,

        ConnectEnum_S,
        ConnectEnum_Z,
        Connect_Any,
        Connect_East,
        Connect_West,
        Connect_East_West,
        Connect_North,
        Connect_North_East,
        Connect_North_West,
        Connect_North_East_West,
        Connect_South,
        Connect_South_East,
        Connect_South_West,
        Connect_South_East_West,
        Connect_North_South,
        Connect_North_South_East,
        Connect_North_South_West,

        FacetEnum_S,
        FacetEnum_Z,
        Facet_None,
        Facet_Nubby,
        Facet_Diamond,
        Facet_InArrow,
        Facet_Force_None,
        Facet_Force_Nubby,
        Facet_Force_Diamond,
        Facet_Force_InArrow,

        CompuTypeEnum_S,
        CompuTypeEnum_Z,
        CompuType_RowValue,
        CompuType_RelatedValue,
        CompuType_NumericValueSet,
        CompuType_CompositeString,
        CompuType_CompositeReversed,

        NumericSetEnum_Z,
        NumericSet_Count,
        NumericSet_Count_Min_Max,
        NumericSet_Count_Min_Max_Sum,
        NumericSet_Count_Min_Max_Sum_Ave,
        NumericSet_Count_Min_Max_Sum_Ave_Std,

        NumericTermEnum_Z,
        BNumericTerm_Count,
        NumericTerm_Min,
        NumericTerm_Max,
        NumericTerm_Sum,
        NumericTerm_Ave,
        NumericTerm_Std,

        StartLineEnum_S,
        StartLineEnum_Z,
        StartLine_Flat,
        StartLine_Square,
        StartLine_Round,
        StartLine_Triangle,

        EndLineEnum_S,
        EndLineEnum_Z,
        EndLine_Flat,
        EndLine_Square,
        EndLine_Round,
        EndLine_Triangle,

        ResultsEnum_S,
        ResultsEnum_Z,
        Results_OneValue,
        Results_AllValues,
        Results_LimitedSet,

        SortingEnum_S,
        SortingEnum_Z,
        Sorting_Unsorted,
        Sorting_Ascending,
        Sorting_Descending,

        TakeSetEnum_S,
        TakeSetEnum_Z,
        TakeSet_First,
        TakeSet_Last,
        TakeSet_Both,

        AttatchEnum_S,
        AttatchEnum_Z,
        Attatch_Normal,
        Attatch_Radial,
        Attatch_RightAngle,
        Attatch_SkewedAngle,

        LineStyleEnum_Z,
        LineStyle_PointToPoint,
        LineStyle_SimpleSpline,
        LineStyle_DoubleSpline,

        DashStyleEnum_Z,
        DashStyle_Solid,
        DashStyle_Dashed,
        DashStyle_Dotted,
        DashStyle_DashDot,
        DashStyle_DashDotDot,
    }
}
